
def Fashion_array():
    arr = [(r'hi|hello', ['Hello!', 'Hi there!', 'Hey!']),
        (r'bye|goodbye', ['Goodbye!', 'See you later!', 'Bye!']),
        (r'my favorite color is (.*)', ['That\'s a nice color choice!', 'I like that color too.']),
        (r'I like to wear (.*)', ['That\'s a great choice of clothing!', 'Nice preference!']),
        (r'I prefer (.*) brand', ['Brands are important! Which brands do you like?', 'Tell me more about your favorite brands.']),
        (r'I love (.*) style', ['Styles say a lot about a person! Could you elaborate on that?', 'Interesting! What do you like about that style?']),
        (r'I prefer (.*) brands', ['Brands are important! Which brands do you like?', 'Tell me more about your favorite brands.']),
        (r'material should be (.*)',['That is comfortable','Its a great choice for this season']),
        (r'I love (.*) style', ['Styles say a lot about a person! Could you elaborate on that?', 'Interesting! What do you like about that style?']),
        (r'my age is (\d+)', ['You\'re {} years old? Fashion preferences can change with age!', 'Age plays a role in fashion.']),
        (r'I live in (.*)', ['Living in {} sounds interesting! How does it influence your fashion choices?']),
        (r'(.*)', ['I hear you. Tell me more about fashion.', 'Fashion is fascinating! Could you tell me more?']),
    ]
    brands = [
        "ADIDAS", "Allen Solly", "Ap'pulse", "BEWAKOOF", "Billion", "Christy World", "Dressberry", "FLYING MACHINE",
        "GINI & JONY", "HERE&NOW", "HIGHLANDER", "HRX by Hrithik Roshan", "JACK & JONES", "KILLER", "Kuchipoo",
        "LAYA", "LEVI'S", "Mast & Harbour", "MAX", "METRONAUT", "Miss & Chief", "NIKE", "Pantaloons Junior",
        "PEOPLE", "Pepe Jeans", "PETER ENGLAND", "Peter England University", "PROVOGUE", "PUMA", "REEBOK", "Roadster",
        "SLAZENGER", "Spykar", "THE DRY STATE", "TOMMY HILFIGER", "TRIPR", "U.S. POLO ASSN.",
        "United Colors of Benetton",
        "VAN HEUSEN", "Wildcraft", "WROGN", "Widersoft", "Kiba Retail", "KALT", "INKKR", "Printcomet", "BEING HUMAN",
        "FTX", "Restore", "BLIVE", "Exoctic Silver", "Maleno", "NB NICKY BOY", "Jangoboy", "JOCKEY", "Deccan Store",
        "AUSK", "Bullmer", "PRINTWEAR", "V-MART", "DUKE", "Triptee", "UNIQ", "Adorbs", "womenchoice", "Aseria",
        "WildSkin", "Moordale", "The Souled Store", "Cruister", "Jump Cuts", "addiz", "Boodbuck", "LYRISS",
        "London Hills",
        "LOUIS PHILIPPE", "JT SMART", "Arrow Sport", "BGLORE", "EyeBogler", "TECHNOSPORT", "Fabflee", "Smartees",
        "FADMARK", "NagarFashion", "UrGear", "STYLOGUE", "Leotude", "NITYANAND CREATIONS", "Abhirocks", "Arbour",
        "GNS National", "rjm", "CAMPUS SUTRA", "RELANE", "Tivy", "VIMAL JONNEY", "Polo Plus", "GNS", "FOREVER 21",
        "White Moon", "JUGULAR", "RED TAPE", "Trendfull", "Adrenex", "MANIAC", "MOONVELLY", "SYDNEY HILLS",
        "STYLHACKER",
        "Coldplay", "WEAR YOUR OPINION", "HELMONT", "bigbanana", "Viralee Retail", "MIYA", "Status Quo",
        "Calvin Klein Jeans", "PARX", "LIME", "cooft", "THE BLAZZE", "CHKOKKO", "3BROS", "Magneto",
        "DIFFERENCE OF OPINION",
        "Classic Polo", "UDI n ADI", "FastColors", "INDICLUB", "Bribzy", "Gomars", "DISNEY BY MISS & CHIEF",
        "London Crew",
        "teky", "La Milano", "DILLINGER", "FERANOID", "CHOZI", "Organic Chics", "Veirdo", "FRISKERS", "Try This", "ONN",
        "Unite Wear", "Jaskart", "CANTABIL", "INDIZO", "DUDEME", "Canis", "Pagalpan", "The Million Club", "Hellcat",
        "CLOTHINKHUB", "ADRO", "Tee Gallery", "MUFTI", "Fashion And Youth", "tfurnish", "UNIBERRY", "Alan Jones",
        "KAJARU",
        "Wrangler", "Sztori", "MONTE CARLO", "MAGNUM", "MONKEY BOYS", "Aaramkhor", "PARK AVENUE", "GEUM",
        "Free Authority",
        "Austivo", "Kroptee", "Byford by Pantaloons", "KOMY", "krishnafit", "privic", "PRORIDERS", "Trond",
        "Lieo Trend",
        "R09INE", "M7 By Metronaut", "Broyz", "KETCH", "RITZEES", "BEYOU FASHION", "ONECENTRE", "LazyChunks", "LEE",
        "Ekom", "TQH", "Axxitude", "VeBNoR", "FARBOT", "ALCIS", "FIONAA TRENDZ", "QUIN FLETCHER", "Oosh", "We Perfect",
        "PAUSE Sport", "rino", "Lawful Casual", "kidsville", "Camfoot", "Be Crazy", "Gritstones", "Wild West",
        "NAUTICA",
        "BLISSINK", "Silver Swan", "TEEMEX", "First Krush", "Celebrino", "KIDZEE", "Neoamber", "LA ORCHIS", "Camey",
        "dyrectdeals", "Louis Philippe Sport", "FastB", "Lux Nitro", "Art Attack Gallery", "CELSIUS", "TKN TOPPERS",
        "DOKCHAN", "Young trendz", "Wrath", "QuirkyKicks", "Gentino", "Banotrendy", "Merriment", "ITBD", "Cryptic",
        "AEROPOSTALE", "Exocticaa", "Urban Tailor", "Calm Down", "John Peters", "PERF", "Aman Textile", "Stelino",
        "PAM", "OGEN", "PHINSTAR", "RENUOVO", "CLOFLIX", "E-MAX", "Urbano Plus", "TRENDY DUNIYA", "Madfrog", "GLITO",
        "Crastic", "Urbano Fashion", "TeeWink", "Behemoth", "Derkley", "ELBATROSS", "Concepts", "YI FASHION",
        "Stellers", "MARVEL BY MISS & CHIEF", "Club York", "Black Collection", "MYO", "Lecowar", "Boxmen", "BUKKL",
        "U.S. Polo Assn. Denim Co.", "BERRYBLUES", "PP PRODUCTIONS", "ELEGANT FOX", "Blackberrys", "Outsize",
        "American Eagle Outfitters", "SLOWLORIS", "SCOTT INTERNATIONAL", "PROZO", "WOLFHEAD", "DUCATI", "Pytton", "Dam",
        "My Tshirt", "FREELY", "THUNDER PLANET", "INDIAN TERRAIN", "BASE 41", "clickwell", "Missille",
        "PERFECT PRODUCTION", "MANHOOD", "ARROW", "af collection", "ZEN1FASHION", "Think Tech", "CLAfoutis",
        "STYLE FAST",
        "MADE IN THE SHADE", "LGGARMENTS", "CRIMSOUNE CLUB", "COUNTRY YARD", "PROMOUNT", "FLYIND VOGUE OUTFIT", "Autna",
        "satyuga", "SHOEFLY", "Besick", "New Trends Collection", "Money Leaf", "Gibbs", "Distortion Crew", "RIGO",
        "Lycos",
        "Kore Cloting Point", "Fleximaa", "American Crew", "TEEFOX", "TUCK INN", "Manlino", "DREAMSELLERS",
        "AVA Fashion",
        "4M SALES", "WRAGLON", "Uniplanet Store", "TLF", "Gkidz", "Rock.it", "RABBY", "True Basket", "Galatea",
        "Cool Plus",
        "MAMYBEAR", "Kryptic", "DIAZ", "Allen Solly", "CHEROKEE", "Dressberry", "FLYING MACHINE", "GINI & JONY",
        "HERE&NOW",
        "Herway", "HIGHLANDER", "JACK & JONES", "KILLER", "KOTTY", "LEE", "LEVI'S", "Louis Philippe Jeans",
        "Mast & Harbour",
        "MAX", "METRONAUT", "Miss & Chief", "Miss Chase", "MONTE CARLO", "MUFTI", "NUMERO UNO", "Pantaloons Junior",
        "PEOPLE",
        "Pepe Jeans", "PETER ENGLAND", "PROVOGUE", "Roadster", "SASSAFRAS", "Spykar", "Tokyo Talkies", "TOMMY HILFIGER",
        "U.S. POLO ASSN.", "United Colors of Benetton", "Urbanic", "VAN HEUSEN", "VERO MODA", "Wrangler", "WROGN",
        "Lzard",
        "V-MART", "Masterly Weft", "FLAYING", "MULTIBRAAND FASHION", "MEGHZ", "LOUIS PHILIPPE", "STUDIO NEXX", "INAAYA",
        "Urbano Fashion", "AWACK", "CANTABIL", "RASSO", "Lawson", "The Indian Garage Co.", "FEVER", "comfits",
        "Crishtaliyo",
        "2fashion", "American Eagle Outfitters", "Halogen", "FOREVER 21", "German Club", "linaria", "UNITED DENIM",
        "KETCH",
        "CRIMSOUNE CLUB", "DUKE", "High Star", "Perfect Outlet", "BEING HUMAN", "CKUSH", "fashionatractio", "Jade Blue",
        "GRADELY", "Fandom Collection", "Showoff", "Addiction", "Greenfibre", "Blackberrys", "LAWMAN PG3",
        "U.S. Polo Assn. Denim Co.",
        "ZAYSH", "DELEXO", "StyleNFit", "LAHSUAK", "CAMPUS SUTRA", "BEN MARTIN", "PERFECT FASHION", "Styzon", "SWWAG",
        "INDUSPOLO",
        "INDIAN TERRAIN", "FAME FOREVER", "Canary London", "EVERBLUE", "Passion", "POKHINDA", "C2FH", "ONLY",
        "American Bull",
        "SheLook", "Urbano Plus", "YU by Pantaloons", "FabTag", "SF Jeans by Pantaloons", "PARX", "La Creacion",
        "VOI JEANS",
        "TRAFFICJAM", "X20", "TISTABENE", "beauty", "asaba", "white apple jns", "NEHA FASHION", "FCK-3", "ClubRocks",
        "Calvin Klein Jeans", "TAPA", "fineblu", "Rend", "RED CHIEF", "Crishtaliyo", "SELECTED HOMME",
        "TALES & STORIES",
        "Marsh-X", "PODGE", "Moudlin", "Jean Cafe", "holy chic", "DOLCE CRUDO", "Dewdesign", "Celio", "french crown",
        "Creatywitty", "GUTI", "iVOC", "Arrow Sport", "HOFFMEN", "DUNDUBHI", "markview", "Orijean", "TCI", "JOHN PRIDE",
        "CALCIUM", "Dais", "Xee", "SASOKI", "GOLD-D.A FASHION", "Buzzic", "MANTOCK", "MADAME", "Gods Club",
        "The Alice's",
        "JUST BLACK", "M.R. FASHION", "Sobbers", "SENDIPO", "SAVITA FASHION WEAR", "BOTUMQUTE", "Instafab Plus",
        "mevan",
        "RAGZO", "RJ DENIM", "flete", "INTEGRITI", "CEFALU", "BADMAASH", "AD by Arvind", "jac fashion",
        "Ira Collections",
        "Glossia", "RIG BONE", "Nifty", "Ginger by Lifestyle", "Belliskey", "LLAK", "MOD", "Zizvo", "NIVASU",
        "Moda Rapido",
        "M MODDY", "Crazeis", "Vidale Clothing", "Robecult", "Gabon", "Allen Cooper", "TURTLE", "DENNIE FOSTE",
        "screwy",
        "MAVI Fashion", "Cordiano", "Rocking Swamy", "PROTE", "AngelFab", "EditLook", "TNG", "Colt", "COLORPLUS",
        "Nibonic",
        "PX4 JEANSWEAR", "PLUSS", "Supernova Inc.", "NIKNVIL", "F2M", "true colors of india", "OXEMBERG",
        "Veneto Brooks",
        "DRRAGON", "Qeboo", "Blu Gravity Life after Denim", "Star4well", "Fancycool", "Black Horse", "SPARKY", "TYFFYN",
        "YNC", "quesha", "American indigo", "Kcoy", "NEON-9", "FORCA", "flying girls", "GLAMHOOD", "Glamica", "Harvard"]
    colors = [
        "White", "Black", "Gray", "Silver", "Charcoal", "Red", "Maroon", "Burgundy", "Pink", "Coral",
        "Orange", "Peach", "Yellow", "Gold", "Lemon", "Green", "Lime", "Olive", "Teal", "Turquoise",
        "Blue", "Navy", "Cobalt", "Indigo", "Violet", "Purple", "Lavender", "Magenta", "Fuchsia",
        "Brown", "Beige", "Tan", "Khaki", "Cream", "Ivory", "Mint", "Aqua", "Salmon", "Crimson",
        "Sky Blue", "Rust", "Sage", "Bronze", "Plum", "Lilac", "Apricot", "Terracotta", "Emerald",
        "Chocolate", "Sapphire", "Ruby", "Cyan", "Amber", "Aquamarine", "Cerulean", "Pearl", "Topaz",
        "Vermilion", "Turmeric", "Mauve", "Chartreuse", "Bisque", "Sienna", "Moccasin", "Periwinkle",
        "Slate", "Cornsilk", "Khaki", "Bisque", "Wheat", "Honeydew", "Lavender", "Misty Rose", "Sea Green",
        "Azure", "Old Lace", "Navajo White", "Papaya Whip", "Antique White", "Linen", "Ghost White",
        "Snow", "Floral White", "Gainsboro", "Alice Blue", "Ivory Black", "Beau Blue", "Bright Cerulean",
        "Baby Blue", "Candy Apple Red", "Crimson Glory", "French Fuchsia", "Lemon Curry", "Screamin' Green",
        "Royal Purple", "Middle Blue", "Mango Tango", "Medium Lavender Magenta", "Maximum Blue", "Ultramarine"
    ]
    fashion_items = [
        "Shirt","T-shirt","tshirt", "Polo Shirt", "Tank Top", "Sweater", "Hoodie", "Jacket", "Blazer", "Coat",
        "Jeans", "Trousers", "Chinos", "Shorts", "Sweatpants", "Leggings", "Skirt", "Dress",
        "Suit", "Tuxedo", "Wedding Dress", "Jumpsuit", "Bikini", "Swimsuit", "Lingerie", "Pajamas",
        "Socks", "Stockings", "Tights", "Underwear", "Bra", "Boxers", "Briefs", "Vest", "Undershirt",
        "Hat", "Cap", "Beanie", "Beret", "Sunhat", "Headband", "Scarf", "Gloves", "Mittens",
        "Belt", "Tie", "Bowtie", "Necktie", "Suspenders", "Shoes", "Sneakers", "Boots", "Sandals",
        "Flip Flops", "High Heels", "Loafers", "Oxfords", "Flats", "Espadrilles", "Wedges", "Mules",
        "Backpack", "Handbag", "Tote Bag", "Clutch", "Messenger Bag", "Satchel", "Briefcase", "Wallet",
        "Watch", "Bracelet", "Necklace", "Earrings", "Ring", "Sunglasses", "Glasses", "Cufflinks",
        "Tights", "Umbrella", "Belt", "Bowler Hat", "Fascinator", "Cape", "Poncho", "Pocket Square",
        "Bolero", "Bodysuit", "Corset", "Cummerbund", "Cummerbund", "Stole", "Shawl", "Pashmina",
        "Anklet", "Belly Chain", "Toe Ring", "Armlet", "Bangle", "Brooch", "Lapel Pin", "Tiara",
        "Visor", "Wristband", "Arm Warmers", "Leg Warmers", "Sarong", "Sarouel Pants", "Kilt", "Kerchief",
        "Duffel Bag", "Fanny Pack", "Gaiters", "Gauntlets", "Gusset", "Insoles", "Keffiyeh",
        "Keychain", "Lanyard", "Leggings", "Messenger Bag", "Money Belt", "Pocket Protector",
        "Shoehorn", "Shoe Tree", "Sleeve Garters", "Spats", "Suspenders", "Tights", "Tote Bag",
        "Trilby", "Turbans", "Umbrella Hat", "Visor", "Wallet", "Waterproof Bag", "Wedding Veil",
        "Kurta", "Sari", "Lehenga", "Sherwani", "Salwar Kameez", "Anarkali Suit", "Dhoti", "Pathani Suit",
        "Churidar", "Patiala Suit", "Bandhani", "Phulkari", "Dupatta", "Jhumkas", "Maang Tikka",
        "Nath", "Chooda", "Bangles", "Kada", "Bindi", "Payal", "Kolhapuri Chappals", "Mojaris",
        "Potli Bag", "Kanchipuram Sari", "Banarasi Sari", "Choli", "Ghagra Choli", "Bridal Veil"
    ]

    city_clothes_dict = {
        "New York": ["Jeans", "T-shirt", "Jacket"],
        "Paris": ["Dress", "Beret", "Scarf"],
        "Tokyo": ["Kimono", "Yukata", "Hakama"],
        "London": ["Suit", "Raincoat", "Umbrella"],
        "Tirupati": ["Traditional Dhoti", "Angavastram", "Kanduva"],
        "Mumbai": ["Sari", "Kurta", "Salwar Kameez"],
        "Delhi": ["Kurta", "Pants", "Dupatta"],
        "Bangalore": ["Jeans", "T-shirt", "Kurti"],
        "Chennai": ["Veshti", "Shirt", "Angavastram"],
        "Jaipur": ["Lehenga", "Bandhini Dupatta", "Rajasthani Safa"],
        "Kolkata": ["Sari", "Kurta", "Dhoti"],
        "Hyderabad": ["Sherwani", "Kurta Pajama", "Pathani Suit"],
        "Ahmedabad": ["Kediyu", "Chorno", "Bandhni Dupatta"],
        "Pune": ["Jeans", "Kurta", "Pheta"],
        "Lucknow": ["Kurta Pajama", "Chikan Sari", "Angarkha"],
        "Chandigarh": ["Salwar Kameez", "Patiala Suit", "Turban"],
        "Coimbatore": ["Veshti", "Shirt", "Angavastram"],
        "Kochi": ["Set Mundu", "Blouse", "Kasavu Sari"],
        "Agra": ["Petha Kurta", "Churidar", "Dupatta"],
        "Varanasi": ["Sari", "Kurta Pajama", "Angarkha"]
    }

    return fashion_items,colors,brands

def trend_check():
    array_fashion = [ '#sweatshirt', '#highwaistjeans', '#sharara', '#bellbottom', '#bomberjacket', '#leggings', '#vintageshirt', '#kimonocardigan', '#boilersuit', '#puffsleeves', '#coldshoulder', '#croptop', '#joggers', '#buckethat', '#poloshirt', '#sweatpants', '#rippedjeans', '#kaftandress', '#gown', '#cargopants', '#denimjacket', '#miniskirt', '#bratop', '#ponchos', '#polkadotdress', '#meshtop', '#hoodie', '#pullover', '#stripedshirt', '#jeggings', '#trenchcoat', '#waistcoat', '#blazer', '#offshoulder', '#denimshorts', '#loungewear', '#chinos', '#pencilskirt', '#floraldress', '#dhotipants', '#skaterdress', '#harempants', '#tees', '#dungaree', '#corset', '#peplumtop', '#jumpsuit', '#anarkalidress', '#lehenga', '#maxidress', '#yogapants', '#sherwani', '#sequencedress','#capri', '#oneshouldertop', '#trouser', '#tanktop', '#tubetop', '#satindress','#bodycondress', '#halterneck', '#poloneck', '#bikershort', '#camisole']
    return array_fashion